name: positional_encodings
channels:
  - anaconda
  - nvidia
  - conda-forge
dependencies:
  - datasets
  - pandas
  - pytorch-gpu
  - pytorch-lightning
  - torchvision
  - transformers
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm